services:
  - type: web
    name: news-app-backend
    runtime: python
    plan : free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    preDeployCommand: alembic upgrade head
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: 'false'
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: CURRENTS_API_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: SOLANA_MODE
        value: MAINNET
      - key: SOLANA_RPC_URL
        sync: false
      - key: SOLANA_MERCHANT_WALLET
        sync: false
